### ISSUE TITLE
Unable to use gitlab as remote repo

### ISSUE THREAD

**Issue by brewmanz** [alanxz/rabbitmq-c#437] opened 2017-09-06 23:00 UTC
I've cloned rabbitmq-c to a local repo (setting this github one as remote 'upstream') and created a gitlab repo as another remote 'originGL'. 
BTW git version 1.9.1, ubuntu 14.04 LTS, 64-bit, usually use CollabNet GitEye for git repo stuff
When I try to push to gitlab via CLI (to remove GitEye from issue), I get:
```
~/git/rabbitmq-c$ git push -u originGL --all
Username for 'https://gitlab.com': XXXX
Password for 'https://XXXX@gitlab.com': 
Counting objects: 4784, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (1552/1552), done.
Writing objects: 100% (4784/4784), 1.71 MiB | 118.00 KiB/s, done.
Total 4784 (delta 3189), reused 4784 (delta 3189)
remote: error: object 3cb254d902a9b226bf95696af3a98839bb7797a4: badDate: invalid author/committer line - bad date
remote: fatal: Error in object
error: unpack failed: index-pack abnormal exit
To https://gitlab.com/XXXX/rabbitmq-c.git
 ! [remote rejected] master -> master (unpacker error)
error: failed to push some refs to 'https://gitlab.com/XXXX/rabbitmq-c.git'
```
I have deleted the gitlab repo and recreated it - same result.

The strange thing is, I can succesfully do the same thing with BitBucket (maybe it's more forgiving?)

**Comment by alanxz** [comment] 2017-09-07 05:24
This is a duplicate of #372, see the workaround there.

**Closed by alanxz** 2017-09-07 05:24 UTC

**Comment by brewmanz** [comment] 2017-09-07 22:59
This does seem seem to be quite a duplicate of #372 . I have applied suggested fix, to no avail.
Following log shows fsck issue, get version (compiled from source), fsck suggested fix, fsck skipped, push to gitlab failing:
```
~/git/rabbitmq-c$ git fsck
Checking object directories: 100% (256/256), done.
error in commit 3cb254d902a9b226bf95696af3a98839bb7797a4: badDate: invalid author/committer line - bad date
Checking objects: 100% (5826/5826), done.
~/git/rabbitmq-c$ git --version
git version 2.14.1.dirty
~/git/rabbitmq-c$ git config fsck.skiplist "$PWD/.git/skiplist"
~/git/rabbitmq-c$ echo 3cb254d902a9b226bf95696af3a98839bb7797a4 >>.git/skiplist
~/git/rabbitmq-c$ git fsck
Checking object directories: 100% (256/256), done.
Checking objects: 100% (5826/5826), done.
~/git/rabbitmq-c$ git push -u originGL --all
Username for 'https://gitlab.com': XXXX
Password for 'https://XXXX@gitlab.com': 
Counting objects: 4784, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (1551/1551), done.
Writing objects: 100% (4784/4784), 1.71 MiB | 132.00 KiB/s, done.
Total 4784 (delta 3190), reused 4784 (delta 3190)
remote: error: object 3cb254d902a9b226bf95696af3a98839bb7797a4: badDate: invalid author/committer line - bad date
remote: fatal: Error in object
error: remote unpack failed: index-pack abnormal exit
To https://gitlab.com/XXXX/rabbitmq-c.git
 ! [remote rejected] master -> master (unpacker error)
error: failed to push some refs to 'https://gitlab.com/XXXX/rabbitmq-c.git'
~/git/rabbitmq-c$ 
```

**Comment by alanxz** [comment] 2017-09-08 02:19
> `remote: error: object 3cb254d902a9b226bf95696af3a98839bb7797a4: badDate: invalid author/committer line - bad date`

Indicates to me that something on gitlab's end is performing this check.  I'm not familiar with how gitlab works, I'd check with them next.
