### ISSUE TITLE
amqp_socket_open to port without listener appears to block forever

### ISSUE THREAD

**Issue by sigiesec** [alanxz/rabbitmq-c#346] opened 2016-04-01 14:13 UTC
In librabbitmq-c 0.5.2, trying to amqp_socket_open to a port where no one was listening, resulted in an AMQP_STATUS_SOCKET_ERROR (unfortunately, the exact socket error could not be determined, cf. https://github.com/alanxz/rabbitmq-c/issues/236, but it should probably have been WSAECONNREFUSED (10061) ).

In librabbitmq-c 0.7.1, this behavior has changed, amqp_socket_open now appears to block forever, and amqp_socket_open_noblock completes with a AMQP_STATUS_TIMEOUT
 
This is unfortunate, as the condition can no longer be distinguished from a real timeout, and the operation only fails after the timeout period.

Has the behaviour changed for a reason? Can the original behaviour be restored?

**Comment by alanxz** [comment] 2016-04-03 06:05
That seems like a bit of a regression. Could you try it out using the current master branch?

I'll do a bit of investigation.

**Comment by sigiesec** [comment] 2016-04-04 13:26
I checked it with the current master branch, and it seems to be back to the previous behaviour with AMQP_STATUS_SOCKET_ERROR. Still, I cannot determine the socket error code, but it is reasonable to assume that there is no other socket error.

**Comment by sigiesec** [comment] 2016-04-06 12:46
Is there a chance to release a fixed 0.7.2 version?

**Comment by alanxz** [comment] 2016-04-06 14:19
I'm trying to get 0.8.0 out the door, but I haven't found and evening to wrap it up. I'll try and aim to get that done in the next ~week.

**Comment by sigiesec** [comment] 2016-04-06 14:55
Ok :) Will 0.8.0 introduce any incompatible changes?

**Comment by alanxz** [comment] 2016-04-06 15:50
Unless you use one of the non-OpenSSL SSL backends I don't see any incompatible changes. Looking for API changes, this may also be called 0.7.2.

**Comment by alanxz** [comment] 2016-04-10 05:19
This was a duplicate of #297. 

v0.8.0 has been released.

**Closed by alanxz** 2016-04-10 05:19 UTC
Labels: bug, duplicate

**Comment by sigiesec** [comment] 2016-04-13 08:04
Thanks, 0.8.0 works fine :)
